run-dist:
	./build/install/app/bin/app

build:
	./gradlew clean build

run:
	./gradlew run

build-run: build run

report:
	./gradlew jacocoTestReport

test:
	./gradlew test

linter:
	./gradlew checkstyleMain

.PHONY: build