/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.concurrent.Callable;

import hexlet.code.parser.ParserFactory;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(
    name = "gendiff",
    mixinStandardHelpOptions = true,
    version = "0.5",
    description = "Compares two configuration files and shows a difference."
)
public class App implements Callable<Integer> {
    @Option(names = {"-f", "--format"}, description = "output format [default: stylish]", paramLabel = "format")
    String format = "stylish";

    @Parameters(index = "0", description = "path to first file", paramLabel = "filepath1")
    String filepath1;
    @Parameters(index = "1", description = "path to second file", paramLabel = "filepath2")
    String filepath2;

    @Override
    public Integer call() throws Exception {
        var file1 = new ParserFactory().createParser(filepath1).getData();
        var file2 = new ParserFactory().createParser(filepath2).getData();
        System.out.println(Differ.generate(file1, file2));
        return 0;
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}
